# Default values for load-balancer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: nginx:1.19.9-alpine
service: 
  internalPort: 443
  externalPort: 443
  type: LoadBalancer
  selector:
    app: nginx