# Default values for load-balancer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: waaler/altinn-designer:latest
service: 
  internalPort: 5000
  externalPort: 3000
  type: NodePort  

env:
- name: ASPNETCORE_ENVIRONMENT
  value: "Development"
- name: "ASPNETCORE_URLS"
  value: "http://+:5000"
- name: "ServiceRepositorySettings__RepositoryLocation"
  value: "/repos/"
- name: "ServiceRepositorySettings__ApiEndPoint"
  value: "http://altinn-repositories:3000/api/v1/"
- name: "ServiceRepositorySettings__ApiEndpointHost"
  value: "altinn-repositories"
- name: "ServiceRepositorySettings__GiteaLoginUrl"
  value: "https://pi.altinn.studio/repos/user/login"
- name: "GeneralSettings__HostName"
  value: "pi.altinn.studio"
- name: "ServiceRepositorySettings__RepositoryBaseURL"
  value: "http://altinn-repositories:3000"
- name: "GeneralSettings__LanguageFilesLocation"
  value: "Languages/"  
- name: "GeneralSettings__CheckTeamMembershipForDeploy"
  value: true
- name: "GeneralSettings__TemplateLocation"
  value: "Templates/AspNet"
- name: "GeneralSettings__DeploymentLocation"
  value: "Templates/AspNet/deployment"
- name: "GeneralSettings__AppLocation"
  value: "Templates/AspNet/App"

