apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}      
        env: 
        {{- range $env := .Values.env }} 
        - name: {{ $env.name }}
          value: {{ $env.value | quote }}
        {{- end }}
        volumeMounts:
        - name: repos
          mountPath: /repos          
      volumes:
      - name: repos
        persistentVolumeClaim:
          claimName: local-path-pvc

        